
from pyop.exceptions import OAuthError

class UserNotAuthenticated(OAuthError):
    pass
